class types:
    parent_page = 'https://kingfisher.kz'

    product_to_name = {
        'moreprodukty_krevetki': 'https://kingfisher.kz/moreprodukty/krevetki/',
        'moreprodukty_kraby': 'https://kingfisher.kz/moreprodukty/kraby/',
        'moreprodukty_ustricy': 'https://kingfisher.kz/moreprodukty/ustricy/',
        'moreprodukty_grebeshok': 'https://kingfisher.kz/moreprodukty/grebeshok/',
        'moreprodukty_midii': 'https://kingfisher.kz/moreprodukty/midii/',
        'moreprodukty_osminogi': 'https://kingfisher.kz/moreprodukty/osminogi/',
        'moreprodukty_lobstery': 'https://kingfisher.kz/moreprodukty/lobstery/',
        'moreprodukty_kalmary': 'https://kingfisher.kz/moreprodukty/kalmary/',
        'moreprodukty_morskoy-kokteyl': 'https://kingfisher.kz/moreprodukty/morskoy-kokteyl/',
        'moreprodukty_vongole': 'https://kingfisher.kz/moreprodukty/vongole/',
        'moreprodukty_morskoy-ezh': 'https://kingfisher.kz/moreprodukty/morskoy-ezh/',
        'moreprodukty_ulitki-burgundskie': 'https://kingfisher.kz/moreprodukty/ulitki-burgundskie/',
        'ryba_ohlazhdennaya-ryba': 'https://kingfisher.kz/ryba/ohlazhdennaya-ryba/',
        'ryba_zamorozhennaya-ryba': 'https://kingfisher.kz/ryba/zamorozhennaya-ryba/',
        'ryba_file-iz-ryby': 'https://kingfisher.kz/ryba/file-iz-ryby/',
        'ryba_ryba-kopchenaya': 'https://kingfisher.kz/ryba/ryba-kopchenaya/',
        'ryba_rifovaya-ryba': 'https://kingfisher.kz/ryba/rifovaya-ryba/',
        'ryba_tunec': 'https://kingfisher.kz/ryba/tunec/',
        'ryba_salmon': 'https://kingfisher.kz/ryba/salmon/',
        'ryba_malosolnaya-ryba': 'https://kingfisher.kz/ryba/malosolnaya-ryba/',
        'ryba_konservy': 'https://kingfisher.kz/ryba/konservy/',
        'ikra_ikra-krasnaya': 'https://kingfisher.kz/ikra/ikra-krasnaya/',
        'ikra_chernaya-ikra': 'https://kingfisher.kz/ikra/chernaya-ikra/',
        'ikra_ikra-morskogo-ezha': 'https://kingfisher.kz/ikra/ikra-morskogo-ezha/',
        'myaso_hamon': 'https://kingfisher.kz/myaso/hamon/',
        'myaso_myaso-utki': 'https://kingfisher.kz/myaso/myaso-utki/',
        'myaso_baranina': 'https://kingfisher.kz/myaso/baranina/',
        'bakaleya_tryufel': 'https://kingfisher.kz/bakaleya/tryufel/',
        'bakaleya_makarony': 'https://kingfisher.kz/bakaleya/makarony/',
        'bakaleya_antipasti': 'https://kingfisher.kz/bakaleya/antipasti/',
        'bakaleya_specii': 'https://kingfisher.kz/bakaleya/specii/',
        'bakaleya_balzamik': 'https://kingfisher.kz/bakaleya/balzamik/',
        'bakaleya_cheeses': 'https://kingfisher.kz/bakaleya/cheeses/',
        'bakaleya_sladosti': 'https://kingfisher.kz/bakaleya/sladosti/',
        'bakaleya_napitki': 'https://kingfisher.kz/bakaleya/napitki/',
        'bakaleya_aziatskaya-kuhnya': 'https://kingfisher.kz/bakaleya/aziatskaya-kuhnya/',
        'bakaleya_ris': 'https://kingfisher.kz/bakaleya/ris/',
        'maslo_olive-oil-barbera': 'https://kingfisher.kz/maslo/olive-oil-barbera/',
        'maslo_olive-oil-finca-la-torre': 'https://kingfisher.kz/maslo/olive-oil-finca-la-torre/',
        'maslo_kokosovoe-maslo': 'https://kingfisher.kz/maslo/kokosovoe-maslo/',
        'maslo_kunzhutnoe-maslo': 'https://kingfisher.kz/maslo/kunzhutnoe-maslo/',
        'maslo_avokado-maslo': 'https://kingfisher.kz/maslo/avokado-maslo/',
        'maslo_maslo-slivochnoe': 'https://kingfisher.kz/maslo/maslo-slivochnoe/'
    }

    link_to_product = {
        'https://kingfisher.kz/moreprodukty/krevetki/': 'Креветки',
        'https://kingfisher.kz/moreprodukty/kraby/': 'Крабы',
        'https://kingfisher.kz/moreprodukty/ustricy/': 'Устрицы',
        'https://kingfisher.kz/moreprodukty/grebeshok/': 'Гребешок',
        'https://kingfisher.kz/moreprodukty/midii/': 'Мидии',
        'https://kingfisher.kz/moreprodukty/osminogi/': 'Осьминоги',
        'https://kingfisher.kz/moreprodukty/lobstery/': 'Лобстеры',
        'https://kingfisher.kz/moreprodukty/kalmary/': 'Кальмары',
        'https://kingfisher.kz/moreprodukty/morskoy-kokteyl/': 'Морской коктейль',
        'https://kingfisher.kz/moreprodukty/vongole/': 'Вонголе',
        'https://kingfisher.kz/moreprodukty/morskoy-ezh/': 'Морской Еж',
        'https://kingfisher.kz/moreprodukty/ulitki-burgundskie/': 'Улитки по Бургундски',
        'https://kingfisher.kz/ryba/ohlazhdennaya-ryba/': 'Охлажденная рыба',
        'https://kingfisher.kz/ryba/zamorozhennaya-ryba/': 'Замороженная рыба',
        'https://kingfisher.kz/ryba/file-iz-ryby/': 'Филе из рыбы',
        'https://kingfisher.kz/ryba/ryba-kopchenaya/': 'Рыба Копченая',
        'https://kingfisher.kz/ryba/rifovaya-ryba/': 'Рифовая рыба',
        'https://kingfisher.kz/ryba/tunec/': 'Тунец',
        'https://kingfisher.kz/ryba/salmon/': 'Лосось',
        'https://kingfisher.kz/ryba/malosolnaya-ryba/': 'Малосольная рыба',
        'https://kingfisher.kz/ryba/konservy/': 'Консервы',
        'https://kingfisher.kz/ikra/ikra-krasnaya/': 'Икра Красная',
        'https://kingfisher.kz/ikra/chernaya-ikra/': 'Черная Икра',
        'https://kingfisher.kz/ikra/ikra-morskogo-ezha/': 'Икра Морского Ежа',
        'https://kingfisher.kz/myaso/hamon/': 'Хамон',
        'https://kingfisher.kz/myaso/myaso-utki/': 'Мясо утки',
        'https://kingfisher.kz/myaso/baranina/': 'Баранина',
        'https://kingfisher.kz/bakaleya/tryufel/': 'Трюфель',
        'https://kingfisher.kz/bakaleya/makarony/': 'Макароны',
        'https://kingfisher.kz/bakaleya/antipasti/': 'Антипасти',
        'https://kingfisher.kz/bakaleya/specii/': 'Специи',
        'https://kingfisher.kz/bakaleya/balzamik/': 'Бальзамик',
        'https://kingfisher.kz/bakaleya/cheeses/': 'Сыры',
        'https://kingfisher.kz/bakaleya/sladosti/': 'Сладости',
        'https://kingfisher.kz/bakaleya/napitki/': 'Напитки',
        'https://kingfisher.kz/bakaleya/aziatskaya-kuhnya/': 'Азиатская Кухня',
        'https://kingfisher.kz/bakaleya/ris/': 'Рис Gallo',
        'https://kingfisher.kz/maslo/olive-oil-barbera/': 'Оливковое масло BARBERA',
        'https://kingfisher.kz/maslo/olive-oil-finca-la-torre/': 'Оливковое масло Finca La Torre',
        'https://kingfisher.kz/maslo/kokosovoe-maslo/': 'Кокосовое масло',
        'https://kingfisher.kz/maslo/kunzhutnoe-maslo/': 'Кунжутное масло',
        'https://kingfisher.kz/maslo/maslo-slivochnoe/': 'Авокадо Масло',
        'https://kingfisher.kz/maslo/avokado-maslo/': 'Масло Сливочное'
    }
